server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testingez_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:

  jpa:
    # properties:
    # hibernate.format_sql: TRUE
    # hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org: WARN
    blog: WARN
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor: TRACE

ninja:
  api:
    trivia:
      url: http://localhost:8081/ninja/api/trivia
    facts:
      url: http://localhost:8081/ninja/api/facts
    jokes:
      url: http://localhost:8081/ninja/api/jokes
    quotes:
      url: http://localhost:8081/ninja/api/quotes
    improvements:
      url: http://localhost:8081/ninja/api/improvements
